// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MediaDown(arg1) {
  return window['go']['cmd']['Cmd']['MediaDown'](arg1);
}
